###
GET http://localhost:5000/notes

###
GET https://notes-be-fadhil7-21569344527.us-central1.run.app/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhIiwiaWF0IjoxNzQ4MDg2NzM0LCJleHAiOjE3NDgwOTAzMzR9.coi9UvMdiZit0BPVWFgbMC03MxbKZ7nsHdRzqQyPupA

###
GET http://localhost:5000/users

###
POST https://notes-be-fadhil7-21569344527.us-central1.run.app/register
Content-Type: application/json

{
  "username": "a1",
  "password": "1",
  "confirm_password": "1"
}
###
POST https://notes-be-fadhil7-21569344527.us-central1.run.app/login
Content-Type: application/json

{
  "username": "a",
  "password": "1"
}

###
POST https://notes-be-fadhil7-21569344527.us-central1.run.app/notes
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJhMSIsImlhdCI6MTc0ODA4NjY1MCwiZXhwIjoxNzQ4MDkwMjUwfQ.2MIt73xC_PwKdorYxlUtpOhsNH7v4pw1OQK6WO8fPTE

{
    "matakuliah": "Prak T1",
    "judul": "export sql storage",
    "isi": "post tanpa xampp dengan menggunakan ip cloud storage",
    "deadline": "",
    "userId": 1
}

###
GET http://localhost:5000/token


###
POST https://notes-be-fadhil-21569344527.us-central1.run.app/notes
Content-Type: application/json

{
    "matakuliah": "Prak TCC",
    "judul": "export sql storage",
    "isi": "post tanpa xampp dengan menggunakan ip cloud storage",
    "deadline": ""
}


###
PATCH  http://localhost:5000/notes/14
Content-Type: application/json

{
    "matakuliah": "Prak TCC",
    "judul": "edit sql storage",
    "isi": "edit tanpa xampp dengan menggunakan ip cloud storage",
    "deadline": ""
}

###
DELETE http://localhost:5000/notes/14
