###
GET http://localhost:5000/notes

###
GET http://localhost:5000/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhIiwiaWF0IjoxNzQ4MDgyNjk5LCJleHAiOjE3NDgwODYyOTl9.tJp1NG25CSfWra8ThvFBlV2l5pfs7Pi_ZssJwuJqZNE

###
GET http://localhost:5000/users

###
POST http://localhost:5000/register
Content-Type: application/json

{
  "username": "a",
  "password": "1",
  "confirm_password": "1"
}
###
POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "a",
  "password": "1"
}

###
POST http://localhost:5000/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhIiwiaWF0IjoxNzQ4MDgyNjk5LCJleHAiOjE3NDgwODYyOTl9.tJp1NG25CSfWra8ThvFBlV2l5pfs7Pi_ZssJwuJqZNE

{
    "matakuliah": "Prak T1",
    "judul": "export sql storage",
    "isi": "post tanpa xampp dengan menggunakan ip cloud storage",
    "deadline": "",
    "userId": 1
}

###
GET http://localhost:5000/token


###
POST https://notes-be-fadhil-21569344527.us-central1.run.app/notes
Content-Type: application/json

{
    "matakuliah": "Prak TCC",
    "judul": "export sql storage",
    "isi": "post tanpa xampp dengan menggunakan ip cloud storage",
    "deadline": ""
}


###
PATCH  http://localhost:5000/notes/14
Content-Type: application/json

{
    "matakuliah": "Prak TCC",
    "judul": "edit sql storage",
    "isi": "edit tanpa xampp dengan menggunakan ip cloud storage",
    "deadline": ""
}

###
DELETE http://localhost:5000/notes/14
